### ISSUE TITLE
A success story with threadpoolctl

### ISSUE THREAD

**Issue by nickodell** [joblib/threadpoolctl#122]
Hey, I wanted to say thank-you for threadpoolctl, and tell you about how I'm using it at my company.

I run a lot of ARIMA-based models, and I use a library called pmdarima to automatically pick the best model. The funny thing about that library is that it actually gets faster when restricted to fewer cores.

Your library was instrumental in detecting and fixing this problem. Internally we've seen speedups of 1.8x to 2.1x just from restricting ARIMA to one core, and more if running many models in parallel.

I wrote a blog post about this: https://njodell.com/?p=74

**Comment by GaelVaroquaux** [comment]
Hey Nick,

Thanks a lot for this note. It warms our heart!!

We've advertised it on the twitter of the foundation that finances some of us: https://twitter.com/sklearn_inria/status/1507359926301171712
