### ISSUE TITLE
error triggered by sklearn.cluster.kmeans

### ISSUE THREAD

**Issue by Freakwill** [joblib/threadpoolctl#123]
Method `kmeans.predict()` calls `threadpoolctl` and throws the following error. How do I fix it?

> 
>   File "/usr/local/lib/python3.8/site-packages/sklearn/cluster/_kmeans.py", line 1334, in predict
>     return _labels_inertia_threadpool_limit(
>   File "/usr/local/lib/python3.8/site-packages/sklearn/cluster/_kmeans.py", line 755, in _labels_inertia_threadpool_limit
>     with threadpool_limits(limits=1, user_api="blas"):
>   File "/usr/local/lib/python3.8/site-packages/sklearn/utils/fixes.py", line 314, in threadpool_limits
>     return threadpoolctl.threadpool_limits(limits=limits, user_api=user_api)
>   File "/usr/local/lib/python3.8/site-packages/threadpoolctl.py", line 171, in __init__
>     self._original_info = self._set_threadpool_limits()
>   File "/usr/local/lib/python3.8/site-packages/threadpoolctl.py", line 268, in _set_threadpool_limits
>     modules = _ThreadpoolInfo(prefixes=self._prefixes,
>   File "/usr/local/lib/python3.8/site-packages/threadpoolctl.py", line 340, in __init__
>     self._load_modules()
>   File "/usr/local/lib/python3.8/site-packages/threadpoolctl.py", line 371, in _load_modules
>     self._find_modules_with_dyld()
>   File "/usr/local/lib/python3.8/site-packages/threadpoolctl.py", line 428, in _find_modules_with_dyld
>     self._make_module_from_path(filepath)
>   File "/usr/local/lib/python3.8/site-packages/threadpoolctl.py", line 515, in _make_module_from_path
>     module = module_class(filepath, prefix, user_api, internal_api)
>   File "/usr/local/lib/python3.8/site-packages/threadpoolctl.py", line 606, in __init__
>     self.version = self.get_version()
>   File "/usr/local/lib/python3.8/site-packages/threadpoolctl.py", line 646, in get_version
>     config = get_config().split()
> AttributeError: 'NoneType' object has no attribute 'split'

**Comment by ogrisel** [comment]
Why did you close this? Can you please explain how to reproduce? In particular the output of `sklearn.show_versions()` would help.

**Comment by dwwkelly** [comment]
I can reproduce this with the threadpoolctl example:

`python3.9 -m threadpoolctl -i numpy scipy.linalg
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/site-packages/threadpoolctl.py", line 796, in <module>
    _main()
  File "/usr/local/lib/python3.9/site-packages/threadpoolctl.py", line 792, in _main
    print(json.dumps(threadpool_info(), indent=2))
  File "/usr/local/lib/python3.9/site-packages/threadpoolctl.py", line 124, in threadpool_info
    return _ThreadpoolInfo(user_api=_ALL_USER_APIS).todicts()
  File "/usr/local/lib/python3.9/site-packages/threadpoolctl.py", line 340, in __init__
    self._load_modules()
  File "/usr/local/lib/python3.9/site-packages/threadpoolctl.py", line 371, in _load_modules
    self._find_modules_with_dyld()
  File "/usr/local/lib/python3.9/site-packages/threadpoolctl.py", line 428, in _find_modules_with_dyld
    self._make_module_from_path(filepath)
  File "/usr/local/lib/python3.9/site-packages/threadpoolctl.py", line 515, in _make_module_from_path
    module = module_class(filepath, prefix, user_api, internal_api)
  File "/usr/local/lib/python3.9/site-packages/threadpoolctl.py", line 606, in __init__
    self.version = self.get_version()
  File "/usr/local/lib/python3.9/site-packages/threadpoolctl.py", line 646, in get_version
    config = get_config().split()
AttributeError: 'NoneType' object has no attribute 'split'`

`brew info openblas
openblas: stable 0.3.20 (bottled), HEAD [keg-only]
Optimized BLAS library
https://www.openblas.net/
/usr/local/Cellar/openblas/0.3.20 (23 files, 128.6MB)
  Poured from bottle on 2022-03-14 at 20:43:29`

`HOMEBREW_VERSION: 3.5.2-158-g38e1af8
ORIGIN: https://github.com/Homebrew/brew
HEAD: 38e1af857654b940f52df9b686f31b0b0cce2d17
Last commit: 6 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: a0240681a517411ea09bfce2bfbecccc27538374
Core tap last commit: 5 days ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.yJPIElD4gS/org.xquartz:0
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit icelake
Clang: 13.1.6 build 1316
Git: 2.32.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.3.1-x86_64
CLT: 13.4.0.0.1.1651278267
Xcode: 13.4.1`
