### ISSUE TITLE
Fails on FreeBSD: ld-elf.so.1: Can't find module with TLS index 1

### ISSUE THREAD

**Issue by yurivict** [joblib/threadpoolctl#125]
This code:
```
from threadpoolctl import threadpool_info
from pprint import pprint
pprint(threadpool_info())
```
fails on FreeBSD 13:
```
ld-elf.so.1: Can't find module with TLS index 1
```

**Comment by yurivict** [comment]
@jeremiedbb 

Hi,

Do you have any idea why does threadpoolctl fail on FreeBSD?

Thanks,
Yuri

**Comment by jeremiedbb** [comment]
Hi @yurivict,
sorry for the late answer, I didn't see your issue. I have no idea why it's failing like that, but you'll probably have better chances in the issue that you just opened on cpython https://github.com/python/cpython/issues/92828.

**Comment by ogrisel** [comment]
Is this raising a catchable Python exception or directly crashing the Python interpreter?

**Comment by yurivict** [comment]
Program exits with exit code 1 after the failure message. It doesn't crash.

**Comment by ptrajdos** [comment]
Hi.

According to the discussion in https://github.com/python/cpython/issues/92828
My fix will no longer be needed in FreeBSD 14.

Regards,
Pawel
