### ISSUE TITLE
RFE: please start making github releases

### ISSUE THREAD

**Issue by kloczek** [joblib/threadpoolctl#147]
Is it possible next time on release new version make the github release to have entry on https://github.com/joblib/threadpoolctl/releases? 🤔

I'm asking because only on make gh release is spread notification about new release to those who have set watch->releases.

More about gh releases is possible to find on
https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository

**Comment by jeremiedbb** [comment]
Hi @kloczek, we'll try to make an effort :+1:

**Comment by kloczek** [comment]
Thank you very much 👍 😄 

Few more links which may this easier:
https://cli.github.com/manual/gh_release_upload/
https://github.com/marketplace/actions/github-release
https://pgjones.dev/blog/trusted-plublishing-2023/
https://github.com/jbms/sphinx-immaterial/issues/281#issuecomment-1700933026
tox target to publish on pypi and make gh release https://github.com/jaraco/skeleton/blob/928e9a86d61d3a660948bcba7689f90216cc8243/tox.ini#L42-L58

**Comment by jeremiedbb** [comment]
We published a github release for 3.3.0 and plan to do it for the future releases as well. I think we can close this issue, thanks

**Comment by kloczek** [comment]
Thank you very much 👍 
Just found that my automation was able automatically process email notification about new version successfully upgrading build procedure 😄
