### ISSUE TITLE
Incompatibility with unrelated C libraries whose names begin with certain prefixes (e.g. "libbliss.so")

### ISSUE THREAD

**Issue by rmcgibbo** [joblib/threadpoolctl#149]
Hi,

I'm seeing a crash while creating a thread pool from a Python process that happens to have a library called `libbliss.so` loaded into its address space. [libblis](http://www.tcs.hut.fi/Software/bliss/) is "A Tool for Computing Automorphism Groups and Canonical Labelings of Graphs", and ships a C++ library that can be linked into Python extension modules.

It looks like the basic issue is that the code is looking for any dynamic libraries loaded into the process whose names begin with the string prefix `"libblis"`. Obviously you're looking for https://github.com/flame/blis, but this also matches my `libbliss.so` (extra "s"). And then the code just assumes these libraries export a `bli_info_get_enable_openmp` symbol. It appears that there's no try-except block to protect against loading unrelated libraries with the same filename prefix that don't export a symbol by that name.

Here's a simplified and condensed example that illustrates the core of the problem, tested against the current master (d9736780c09cff75de5c7a3b295aeddd6b8cbf0c).

```
$ python -c 'import ctypes; ctypes.CDLL("./libbliss.so"); import threadpoolctl; threadpoolctl.threadpool_info()'
Exception ignored on calling ctypes callback function: <function ThreadpoolController._find_libraries_with_dl_iterate_phdr.<locals>.match_library_callback at 0x7f7fe9e58820>
Traceback (most recent call last):
  File "/tmp/github-bugreport/threadpoolctl.py", line 847, in match_library_callback
    self._make_controller_from_path(filepath)
  File "/tmp/github-bugreport/threadpoolctl.py", line 984, in _make_controller_from_path
    lib_controller = controller_class(filepath=filepath, prefix=prefix)
  File "/tmp/github-bugreport/threadpoolctl.py", line 113, in __init__
    self.set_additional_attributes()
  File "/tmp/github-bugreport/threadpoolctl.py", line 243, in set_additional_attributes
    self.threading_layer = self._get_threading_layer()
  File "/tmp/github-bugreport/threadpoolctl.py", line 269, in _get_threading_layer
    if self.dynlib.bli_info_get_enable_openmp():
  File "/path/to/our/python/lib/python3.10/ctypes/__init__.py", line 387, in __getattr__
    func = self.__getitem__(name)
  File "/path/to/our/python/lib/python3.10/ctypes/__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: ./libbliss.so: undefined symbol: bli_info_get_enable_openmp
```

**Comment by jeremiedbb** [comment]
Thanks for the report @rmcgibbo. That's unfortunate indeed :/
I think that we have no choice but to look for the symbols before declaring that some lib matches one of our supported libraries then.
