### ISSUE TITLE
Remove libc warning inside Pyodide?

### ISSUE THREAD

**Issue by lesteve** [joblib/threadpoolctl#167]
Inside Pyodide [0.25 console](https://pyodide.org/en/stable/console.html):
```py
import threadpoolctl
threadpoolctl.threadpool_info()
```

```
/lib/python3.11/site-packages/threadpoolctl.py:1019: RuntimeWarning: libc not found. The ctypes module in Python 3.11 is maybe too old for this OS.
```

This can cause a confusing warning when running scikit-learn code so maybe we should consider not warning in this case?

![image](https://github.com/joblib/threadpoolctl/assets/1680079/36a49e71-5922-4c57-a456-932137f35f9c)

`sys.platform == 'emscripten'` seems like a simple way to check that we are inside Pyodide (more generally Python has been compiled for emscripten). See https://pyodide.org/en/stable/usage/faq.html#how-to-detect-that-code-is-run-with-pyodide for more details.

**Comment by jeremiedbb** [comment]
I don't understand why `libc` is not found on emscripten. Maybe it's an issue with ctypes `find_library` ?

**Comment by lesteve** [comment]
I am not 100% sure but my basic understanding is that there is some limited support of `ctypes`  in Pyodide: https://github.com/pyodide/pyodide/issues/728 and https://github.com/pyodide/pyodide/pull/1656.

It may be worth asking in the Pyodide repo whether `ctypes.find_library('c')` makes any sense inside Pyodide or not.

**Comment by lesteve** [comment]
Full disclosure: I don't know how the libc info is used by threadpoolctl ...

**Comment by lesteve** [comment]
I have opened a PR that I think should fix it #169.

While I was looking around, I found this [discussion in the CPython discourse](https://discuss.python.org/t/a-ctypes-function-to-list-all-loaded-shared-libraries/36370) to add a portable way to list the loaded libraries in `ctypes.util`. For now there is a package on PyPI `dllist` https://github.com/WardBrian/dllist. The project seems to be pure Python. There is some some `C` code but only for the tests.

**Comment by jeremiedbb** [comment]
> While I was looking around, I found this [discussion in the CPython discourse](https://discuss.python.org/t/a-ctypes-function-to-list-all-loaded-shared-libraries/36370) to add a portable way to list the loaded libraries in ctypes.util

haha threadpoolctl is one 😄 except that we filter out all the libs we're not interested in. ``dllist`` does essentially the same thing than us, and it always starts by finding libc prior to that.

**Comment by lesteve** [comment]
I guess the dllist original motivation was to (maybe one day) have the functionality in Python stdlib. There may be some hope for dllist which has a smaller scope than threadpoolctl but this is probably not going to happen in the short-term future.

**Comment by hoodmane** [comment]
So part of the problem here is that we have a statically linked libc. So all of the libc symbols are in the main module. But also `dl_iterate_phdr` is missing, I opened an Emscripten issue here:
https://github.com/emscripten-core/emscripten/issues/21354
I could write custom code that would do the same thing in Pyodide but it would be nice if we could fix the issue correctly by providing `dl_iterate_phdr`.

**Comment by jeremiedbb** [comment]
Thanks for the explanation ! Being able to rely on ``dl_iterate_phdr`` would indeed be the best solution for us
