### ISSUE TITLE
can't install using pip

### ISSUE THREAD

**Issue by migel** [joblib/threadpoolctl#20]
```
pip install threadpoolctl
Collecting threadpoolctl
  ERROR: Could not find a version that satisfies the requirement threadpoolctl (from versions: none)
ERROR: No matching distribution found for threadpoolctl
```

**Comment by jeremiedbb** [comment]
There's no release on Pypi yet. We still need to fix a few thing before we can make a first release. However, you can install it from source, following the instructions in the readme.

**Comment by rth** [comment]
It would be good if,
```
pip install https://github.com/joblib/threadpoolctl.git
```
worked. Currently, it doesn't because `setup.py` is missing.

**Comment by ogrisel** [comment]
It works if you install a recent version of pip (e.g. I tried with 19.1.1) and then do:

```
pip install https://github.com/joblib/threadpoolctl.git
```
