### ISSUE TITLE
Can't install on Python2.7 because of flit

### ISSUE THREAD

**Issue by clemisch** [joblib/threadpoolctl#21]
I'm unable to install the library using `pip2 install --user .` because `flit` is not available in Python2.7. Since this is only a single file, is `flit` really necessary?

**Comment by ogrisel** [comment]
As threadpoolctl is being developed by projects (scikit-learn, numpy, ...) who no longer support Python 2 in their development branch I don't think we will put any effort in supporting Python 2.
