### ISSUE TITLE
Just saying thanks

### ISSUE THREAD

**Issue by FabianIsensee** [joblib/threadpoolctl#36]
Awesome work! I just integrated it into my own python package (batchgenerators).

I am just here to say thanks, this is not an issue :-)

Best,
Fabian

**Comment by ogrisel** [comment]
Thanks for saying thanks :) I did not know we had any users yet. And sorry for breaking the API a bit  in the [latest release](https://github.com/joblib/threadpoolctl/blob/master/CHANGES.md#110-2019-09-12).
