### ISSUE TITLE
CI: change python version to 3.8 when scipy wheels are available

### ISSUE THREAD

**Issue by jeremiedbb** [joblib/threadpoolctl#53]
currently python version is pinned to 3.7 for the job `py37_pip_openblas_gcc_clang` because wheels are not yet available. This issue is here to remember to change to 3.8 when they are.

**Comment by ogrisel** [comment]
wheels for which packages?

**Comment by jeremiedbb** [comment]
scipy

**Comment by jeremiedbb** [comment]
latest has already been put back in several jobs
