### ISSUE TITLE
Make threadpool_limits into a decorator

### ISSUE THREAD

**Issue by mimakaev** [joblib/threadpoolctl#69]
We need to set threadpool_limits to basically every function in our package. I found that it would be much easier if threadpool_limits was also a decorator: we won't need to add another indent to our entire codebase, which is good from the code style point of view. 

I believe it could be done easily, by inheriting threadpool_manager from contextlib.ContextDecorator

https://docs.python.org/3/library/contextlib.html#using-a-context-manager-as-a-function-decorator

**Comment by GaelVaroquaux** [comment]
FYI, a significant fraction of the core devs are currently very busy assisting hospitals with data-science challenges to manage best the covid outbreak. There might be significant turn-around times.

**Comment by ogrisel** [comment]
Hi @mimakaev, this is an interesting idea. Feel free to submit a PR (with tests) to implement this faster.

**Comment by yuxuanzhuang** [comment]
Hi! When I tried to convert `threadpool_limits` into a decorator with `ContextDecorator`, the thread limitation seems to have been applied globally. I am wondering if you have a good solution to that.
https://gist.github.com/yuxuanzhuang/05b0da16a51f567e54f7f3f22591e316

**Comment by ogrisel** [comment]
No there is no good solution for this because threadpoolctl talks to the global API of the third party libraries (openmp and blas). It seems that what you want would be to access a thread-local state of those libraries but AFAIK this is not possible.
