### ISSUE TITLE
Problems with starting the module after pip/conda install

### ISSUE THREAD

**Issue by theVmagnificient** [joblib/threadpoolctl#77]
Greetings! I'm having a problem when using threadpoolctl after installation via pip/conda.

![image](https://user-images.githubusercontent.com/42278932/90154468-d6630a00-dd92-11ea-9648-85e0306e1f9d.png)
![image](https://user-images.githubusercontent.com/42278932/90154499-dd8a1800-dd92-11ea-9d92-ac761ed9f458.png)

**Comment by jeremiedbb** [comment]
Hi, thanks for the report. Can you give us more information on your OS and versions of the different packages ?

**Comment by theVmagnificient** [comment]
there was something wrong with .so files. I've just changed name variable connected with .so file and everything is ok now
