### ISSUE TITLE
Missing license field in package metadata

### ISSUE THREAD

**Issue by remram44** [joblib/threadpoolctl#78]
Hi,

It would be helpful if the `license` field could be populated, this helps automated tools. The SPDX identifier for the "new" BSD license is `BSD-3-Clause`, I assume it goes in `pyproject.toml` (I don't use flit, but that's where it goes with Poetry).

Thanks everyone for joblib, and sorry about the nitpick.

**Comment by jeremiedbb** [comment]
Hi @remram44, according to flit's doc ([here](https://flit.readthedocs.io/en/latest/pyproject_toml.html)), it's preferred to specify the license through the `classifiers` field. We do have a trove classifier for the license. Have you found an issue with an automated tool in particular ?

**Comment by remram44** [comment]
pip itself is one: https://github.com/pypa/pip/issues/6677

Somehow the old docs for distutils used to recommend classifiers over the license field, even though that's been officially replaced by setuptools long ago. If tools like flit still say that I'm going to have to start there...

The Python sides seems to be dragging its feed too coming up with a clear recommendation (since PEP 459 has been withdrawn) so if you feel strongly about not adding this field I really can't point you to a doc that says you MUST do it. It's just that tools seem to rely on the `license` field (pip, and pip-licenses in default mode) and that the license field behaves better in the presence of multiple licenses (AND/OR operators).

**Comment by jeremiedbb** [comment]
Thanks for the clarification and sorry for the delay. I guess it can't hurt to add it
