### ISSUE TITLE
Remove filename_prefixes from the dicts returned by get_threadpool_limits

### ISSUE THREAD

**Issue by ogrisel** [joblib/threadpoolctl#8]
I don't think the list of `filename_prefixes` is a useful info for the users introspecting their runtime. If they need this they can read the source code of threadpoolctl.

Also maybe `get_threadpool_limits` should be renamed to `get_threadpool_info`.

**Comment by tomMoral** [comment]
I agree that we should remove `filename_prefix` from the information.

For the name, this would be good, or event `threadpool_info` to mirror `threadpool_limits`. This would also solve the issue of mirroring `get_threadpool_limits` with a `set_threadpool_limits`.
