### ISSUE TITLE
MKL warning (undefined symbol: mkl_get_version_string)

### ISSUE THREAD

**Issue by rachtsingh** [joblib/threadpoolctl#81]
I was pointed here since a downstream project (fil profiler) said that this was a bug in threadpoolctl, but I think the library isn't able to handle our MKL version:

```
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 232, in 'calling callback function'
  File "<PATH>/lib/venv3/lib64/python3.7/site-packages/threadpoolctl.py", line 400, in match_module_callback
    self._make_module_from_path(filepath)
  File "<PATH>/lib/venv3/lib64/python3.7/site-packages/threadpoolctl.py", line 515, in _make_module_from_path
    module = module_class(filepath, prefix, user_api, internal_api)
  File "<PATH>/lib/venv3/lib64/python3.7/site-packages/threadpoolctl.py", line 606, in __init__
    self.version = self.get_version()
  File "<PATH>/lib/venv3/lib64/python3.7/site-packages/threadpoolctl.py", line 711, in get_version
    self._dynlib.mkl_get_version_string(res, 200)
  File "/opt/python/python-3.7/lib64/python3.7/ctypes/__init__.py", line 372, in __getattr__
    func = self.__getitem__(name)
  File "/opt/python/python-3.7/lib64/python3.7/ctypes/__init__.py", line 377, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/local/lib/libmkl_rt.so: undefined symbol: mkl_get_version_string
```

I'm pretty sure the MKL version (as defined by `INTEL_MKL_VERSION`) is `20190004` if that helps.

**Comment by lesteve** [comment]
The context with the original issue: https://github.com/pythonspeed/filprofiler/issues/147

**Comment by jjerphan** [comment]
Hi @rachtsingh,

What do you get listing symbols? You can do so and filter on `version` using :
```sh
nm --demangle --defined-only usr/local/lib/libmkl_rt.so | grep "version"
```

**Comment by jeremiedbb** [comment]
Thanks for the report @rachtsingh.

> I'm pretty sure the MKL version (as defined by INTEL_MKL_VERSION) is 20190004 if that helps.

It's weird because I checked up to mkl 2017 and all have the mkl_get_version_string symbol. could you try to run your program with `MKL_VERBOSE=1` and report the output ?

Anyway, even if we don't understand the cause of the failure, we can protect the version check with a ``try, except`` statement.

**Comment by jeremiedbb** [comment]
> What do you get listing symbols? You can do so and filter on version using :
> nm --demangle /usr/local/lib/libmkl_rt.so | grep "version"

Also, can you tell us the result of `nm --demangle /usr/local/lib/libmkl_rt.so | grep "Version"`. I suspect you only have the `MKL_Get_Version_String` symbol.

**Comment by ogrisel** [comment]
Just to be safe, use `grep -i` (ignore case):

```
nm --demangle /usr/local/lib/libmkl_rt.so | grep -i "version"
```

**Comment by rachtsingh** [comment]
Thank you for the quick response. Both version (-i version and -i Version) didn't return anything, but the entire output seems reasonably small so I can post it here:

```
0000000000202dd8 d _DYNAMIC
0000000000203000 d _GLOBAL_OFFSET_TABLE_
                 w _ITM_deregisterTMCloneTable
                 w _ITM_registerTMCloneTable
                 w _Jv_RegisterClasses
00000000000021d0 r __FRAME_END__
0000000000001fb8 r __GNU_EH_FRAME_HDR
0000000000202dc8 d __JCR_END__
0000000000202dc8 d __JCR_LIST__
00000000002032f0 d __TMC_END__
00000000002032f0 B __bss_start
                 U __ctype_b_loc@@GLIBC_2.3
                 w __cxa_finalize@@GLIBC_2.2.5
00000000000016d0 t __do_global_dtors_aux
0000000000202dc0 t __do_global_dtors_aux_fini_array_entry
0000000000202dd0 d __dso_handle
                 U __errno_location@@GLIBC_2.2.5
0000000000202db0 t __frame_dummy_init_array_entry
                 U __getdelim@@GLIBC_2.2.5
                 w __gmon_start__
                 U __progname_full@@GLIBC_2.2.5
00000000002032f0 D _edata
00000000002032f8 B _end
0000000000001b54 T _fini
0000000000000e50 T _init
                 U chdir@@GLIBC_2.2.5
                 U close@@GLIBC_2.2.5
00000000002032f0 b completed.6355
0000000000001660 t deregister_tm_clones
00000000002030e0 d desco_conf_items
                 U dlerror@@GLIBC_2.2.5
                 U dlopen@@GLIBC_2.2.5
                 U dlsym@@GLIBC_2.2.5
                 U exit@@GLIBC_2.2.5
                 U fchdir@@GLIBC_2.2.5
                 U fclose@@GLIBC_2.2.5
                 U fopen@@GLIBC_2.2.5
                 U fprintf@@GLIBC_2.2.5
0000000000001710 t frame_dummy
                 U free@@GLIBC_2.2.5
                 U fwrite@@GLIBC_2.2.5
                 U getcwd@@GLIBC_2.2.5
                 U getenv@@GLIBC_2.2.5
0000000000203140 d mkl_boolean_items
0000000000203240 d mkl_cbwr_items
0000000000203180 d mkl_interface_items
00000000002031e0 d mkl_threading_items
                 U open@@GLIBC_2.2.5
                 U program_invocation_name@@GLIBC_2.2.5
0000000000001690 t register_tm_clones
0000000000001920 t set_MKL_CBWR
00000000000019e0 t set_MKL_DYNAMIC
0000000000001aa0 t set_MKL_INTERFACE_LAYER
0000000000001750 t set_MKL_NUM_THREADS
0000000000001860 t set_MKL_THREADING_LAYER
0000000000001010 t setupMKL
                 U stderr@@GLIBC_2.2.5
                 U strcasecmp@@GLIBC_2.2.5
                 U strchr@@GLIBC_2.2.5
                 U strerror@@GLIBC_2.2.5
                 U strlen@@GLIBC_2.2.5
                 U strtol@@GLIBC_2.2.5
```

Also, I found that it is a symlink to the 1.8 version:

```
singhrac/> file /usr/local/lib/libmkl_rt.so
/usr/local/lib/libmkl_rt.so: symbolic link to /usr/local/pkgs/mkl-tools-1.8/lib/libmkl_rt.so
```

Maybe there's a stripped version of the MKL lib that we've installed somehow? Here's the output with `MKL_VERBOSE=1`:

```
MKL_VERBOSE Intel(R) MKL 2019.0 Update 4 Product build 20190411 for Intel(R) 64 architecture Intel(R) Advanced Vector Extensions 2 (Intel(R) AVX2) enabled processors, Lnx 2.60GHz lp64 gnu_thread
MKL_VERBOSE SDOT(2,0x7f0c3e22e678,1,0x7f0c3e22e678,1) 2.11ms CNR:AVX2 Dyn:0 FastMM:1 TID:0  NThr:1
```

If you think the problem is resolved in future versions of MKL, I'm happy to ask our systems group to upgrade; in fact it's likely we should since we don't want to run 2 year old versions of MKL anyway.

**Comment by ogrisel** [comment]
> If you think the problem is resolved in future versions of MKL, I'm happy to ask our systems group to upgrade; in fact it's likely we should since we don't want to run 2 year old versions of MKL anyway.

threadpoolctl also started development 2 years ago and we did not face this problem before as far as I know. So it might be cause by a specific installation procedure rather than a specific version of MKL (although I am not sure).

How do you install MKL and numpy / scipy on this system? Do you build numpy and scipy from source to link against MKL? It would be great to reproduce the problem using a docker container for instance (if possible).

In any case, it would be possible to change threadpoolctl to be robust to this missing method and report `version: "unknown"` if this method is missing.

**Comment by jeremiedbb** [comment]
> In any case, it would be possible to change threadpoolctl to be robust to this missing method and report "version": "unknown" if this method is missing.

done in #82, except it returns None because it's what we do for the other libs

**Comment by rachtsingh** [comment]
Sorry, I forgot to respond to this, but unfortunately I can't make a reproducer for a few reasons, but I'm fairly certain we build numpy/scipy from source against MKL (numpy/scipy installed normally as far as I know). Thank you for handling the case, though!
