### ISSUE TITLE
Make it possible to pass pre-inspected modules to threadpool_limit

### ISSUE THREAD

**Issue by ogrisel** [joblib/threadpoolctl#94]
This would be useful for instance in scikit-learn to avoid re-introspecting the runtime each time we want to protect against over-subscription. Runtime introspection can be costly and it is often the case that once we have imported the libraries we are interested in, we do not expect the list of native threadpool modules to change.

More specifically, in the context of scikit-learn, we can assume that the runtimes (BLAS and OpenMP) will not change once we have imported scikit-learn (and recursively scipy to get the Cython level access to BLAS), so it would be more efficient to store the list of modules as a private attribute of the `sklearn` package and then reuse that list whenever we call `threadpool_limit` in scikit-learn estimators.

**Comment by jeremiedbb** [comment]
Implementation started here https://github.com/joblib/threadpoolctl/pull/38, but for a different use case (actually not doable). I can probably reuse it
